### ISSUE TITLE
Add support for new data types

### ISSUE THREAD

**Issue by ChesoiCarmen** [jwcook23/mssql_dataframe#33]
Hi Jason,

As discussed on email, it would be useful to have sql-pandas mapping support for `nchar`, `datetimeoffset`, `datetime` and `numeric`. 
Essentially this would mean extending the `conversion_rules.rules` dataframe from mssql_dataframe.core module.
This is an example of how I attempted to extend this dataframe:

NOTE: in my example, `nchar` is fixed to 2 characters because that's what my example required. I am not sure how would we make that configurable. Maybe it's not possible so instead of adding the `nchar` rule to the base rules list we just configure it on the client side as and when required.

```
extended_conversion_rules = pd.DataFrame.from_records(
    [
        {
            "sql_type": "nchar",
            "sql_category": "character string",
            "min_value": 2,
            "max_value": 2,
            "pandas_type": "string",
            "odbc_type": pyodbc.SQL_VARCHAR,
            "odbc_size": 0,
            "odbc_precision": 0,
        },
        {
            "sql_type": "datetimeoffset",
            "sql_category": "date time",
            "min_value": pd.Timestamp((pd.Timestamp.min + pd.Timedelta(days=1)).date()),
            "max_value": pd.Timestamp(pd.Timestamp.max.date()),
            "pandas_type": "datetime64[ns]",
            "odbc_type": pyodbc.SQL_TYPE_DATE,
            "odbc_size": 34,
            "odbc_precision": 0,
        },
        {
            "sql_type": "datetime",
            "sql_category": "date time",
            "min_value": pd.Timestamp((pd.Timestamp.min + pd.Timedelta(days=1)).date()),
            "max_value": pd.Timestamp(pd.Timestamp.max.date()),
            "pandas_type": "datetime64[ns]",
            "odbc_type": pyodbc.SQL_TYPE_TIMESTAMP,
            "odbc_size": 10,
            "odbc_precision": 0,
        },
        {
            "sql_type": "numeric",
            "sql_category": "approximate numeric",
            "min_value": -(1.79 ** 308),
            "max_value": 1.79 ** 308,
            "pandas_type": "float64",
            "odbc_type": pyodbc.SQL_FLOAT,
            "odbc_size": 8,
            "odbc_precision": 53,
        },
    ])
```

Additionally, we need to change the `sql_spec` method in `mssql_dataframe.core.conversion` module to add `nchar` to the schema.
Specifically, instead of `strings = schema[schema["sql_type"].isin(["varchar", "nvarchar"])].index`,  change as `strings = schema[schema["sql_type"].isin(["varchar", "nvarchar", “nchar”])].index`.

Thank you!

**Comment by jwcook23** [comment]
@ChesoiCarmen I believe these enhancements for new data types will be completed this week.

**Comment by ChesoiCarmen** [comment]
Hi @jwcook23 
Just checking the status of this enhancement: any progress?

**Comment by jwcook23** [comment]
Hi @ChesoiCarmen.
I have added nchar, nvarchar, datetime, and datetimeoffset. All that is left is numeric/decimal which should be straightforward using the Python Decimal data type. I expect a release next week.

**Comment by ChesoiCarmen** [comment]
Sounds great @jwcook23 !

**Comment by ChesoiCarmen** [comment]
hi @jwcook23
just checking if you managed to publish the latest version of the package ?

**Comment by jwcook23** [comment]
@ChesoiCarmen

Version 2 of mssql_dataframe has been released. In Pandas, datetimeoffset is an object of Pandas.Timestamps to prevent the time zone being normalized to UTC for the column. Numeric & decimal are objects of Python Decimals as Pandas doesn't have support for exact numeric. The release of Pandas 2.0 includes the pyarrow backed data types which does support exact numeric. I want to investigate support pyarrow further.

`from decimal import Decimal
import pandas as pd
from mssql_dataframe import SQLServer

sql = SQLServer()

table_name= '##NewDataTypes'
sql.create.table(
    table_name,
    columns = {
        "_numeric": "NUMERIC(5,2)", "_datetime": "DATETIME", 
        "_datetimeoffset": "DATETIMEOFFSET", "_nchar": "NCHAR(3)",
        "PK": "TINYINT"
    },
    primary_key_column = 'PK'
)


df = pd.DataFrame({
    "_nchar": pd.Series(['い', 'え', None], dtype='string'),
    "_datetime": pd.Series(
        ['1900-01-01 00:00:00.008', '1900-01-01 00:00:00.009', None], dtype="datetime64[ns]"
    ),
    "_datetimeoffset": pd.Series(
        ['1900-01-01 00:00:00.123456789+10:30', '1900-01-01 00:00:00.12-9:15', None], dtype="object"
    ),
    "_numeric": pd.Series([Decimal('1.23'), Decimal('4.56789'), None], dtype="object")
}, index=pd.Index([0,1,2], name='PK'))

df = sql.write.insert(table_name, df)

df2 = df.loc[[0]].copy()
df2.at[0,'_numeric'] += Decimal('1.111')
df2.at[0,'_datetime'] += pd.Timedelta(days=1)
df2.at[0,'_datetimeoffset'] += pd.Timedelta(hours=1) 
df2.at[0,'_nchar'] = df2.at[0,'_nchar']*3 
df2 = pd.concat([df2, df2], ignore_index=True)
df2.index = pd.Index([0, 3], name='PK')

df2 = sql.write.merge(table_name, df2, upsert=True)

result = sql.read.table(table_name)`

**Comment by ChesoiCarmen** [comment]
nice one @jwcook23 
thanks for the examples as well
i'll give the new version a try next week
