### ISSUE TITLE
Allow SQLServer type to pass **kwargs to pyodbc.connect

### ISSUE THREAD

**Issue by ChesoiCarmen** [jwcook23/mssql_dataframe#38]
Hi @jwcook23 

Would it be possible to enhance the type SQLServer such that it allows **kwargs to be passed down to the pyodbc.connect?
Essentially the change would consist of:

#1 Changing `SQLServer` __init__ as 
```
def __init__(
...
        **kwargs
    ):
connect.__init__(self, database, server, driver, username, password, **kwargs)
....
)
```
#2 Changing `connect` __init__ as 
```
    def __init__(
...
       **kwargs
    ):
       ....
        if self.connection_spec["trusted_connection"]:
            self.connection = pyodbc.connect(
...
               **kwargs
            )
        else:
            self.connection = pyodbc.connect(
...,
              **kwargs
            )
```

This type of change would allow us to pass into the SQLServer init config like `**{'TrustServerCertificate': 'yes'}` or `**{'Encrypt': 'no'}`, `DSN`, etc

Better yet, i feel that if the SQLServer constructor would just emulate/expose the pyodbc.connect signature, that would be the most flexible as you could connect in various ways.

Let me know what you think about this change or if there is a way of doing it with the current version of the package.

Thank you,
Carmen C.

**Comment by ChesoiCarmen** [comment]
Actually, we also need the `p_str` argument from the pyodbc.connect signature
```
class SQLServer(connect):
    def __init__(
        self,
        p_str: str = "",
        database: str = "master",
        server: str = "localhost",
        driver: str = None,
        username: str = None,
        password: str = None,
        include_metadata_timestamps: bool = False,
        **kwargs
    ):
        connect.__init__(self, p_str, database, server, driver, username, password, **kwargs)
```

**Comment by jwcook23** [comment]
Hi Carmen,Apologies for the delay and thank you for the suggestions. I expect a new version to be released in a few days.On Jul 21, 2023, at 12:26 PM, Carmen Chesoi ***@***.***> wrote:﻿
Actually, we also need the p_str argument from the pyodbc.connect signature
class SQLServer(connect):
    def __init__(
        self,
        p_str: str = "",
        database: str = "master",
        server: str = "localhost",
        driver: str = None,
        username: str = None,
        password: str = None,
        include_metadata_timestamps: bool = False,
        **kwargs
    ):
        connect.__init__(self, p_str, database, server, driver, username, password, **kwargs)

**Comment by MingStar** [comment]
Hi, in v2.0.1, the kwargs argument is still not there

**Comment by jwcook23** [comment]
Hi @ChesoiCarmen  & @MingStar. Version 3.0.0 was just released. SQLServer is now initialized with kwargs that are passed directly to pyodbc.connect.

`    def __init__(self, include_metadata_timestamps: bool = False, **kwargs):
        connect.__init__(self, **kwargs)
`

**Comment by ChesoiCarmen** [comment]
Nice one! Thank you @jwcook23
